In [1]:
import pandas as pd
import numpy as np

     user id | item id | rating | timestamp.
     
     user id | item id | rating |

In [2]:
user_data = pd. read_csv("u.data" , sep="\t" , usecols = [0 ,1 , 2] )
user_data.columns = ["user_id" , "movie_id" , "rating"]
user_data

       user_id  movie_id  rating
0          186       302       3
1           22       377       1
2          244        51       2
3          166       346       1
4          298       474       4
...        ...       ...     ...
99994      880       476       3
99995      716       204       5
99996      276      1090       1
99997       13       225       2
99998       12       203       3

[99999 rows x 3 columns]

In [3]:
col =  "movie_id|movie title|release date|video release date|IMDb URL|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western"

In [4]:
col_names = col.split("|")
col_names

['movie_id',
 'movie title',
 'release date',
 'video release date',
 'IMDb URL',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [5]:
movie_profile = pd.read_csv("u.item", sep="|" , encoding="latin" , header=None , names=col_names , usecols=[0,1])
movie_profile

      movie_id                                movie title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [6]:
final_data = pd.merge(movie_profile, user_data , on = "movie_id")
final_data

       movie_id                                movie title  user_id  rating
0             1                           Toy Story (1995)      308       4
1             1                           Toy Story (1995)      287       5
2             1                           Toy Story (1995)      148       4
3             1                           Toy Story (1995)      280       4
4             1                           Toy Story (1995)       66       3
...         ...                                        ...      ...     ...
99994      1678                          Mat' i syn (1997)      863       1
99995      1679                           B. Monkey (1998)      863       3
99996      1680                       Sliding Doors (1998)      863       2
99997      1681                        You So Crazy (1994)      896       3
99998      1682  Scream of Stone (Schrei aus Stein) (1991)      916       3

[99999 rows x 4 columns]

In [7]:
profile = final_data. pivot_table(values="rating" , index="movie title" , columns= "user_id").fillna(0)
profile

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
movie title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1-900 (1994),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Dalmatians (1996),2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0
12 Angry Men (1957),5.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
187 (1997),0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Guns II (1990),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
"Young Poisoner's Handbook, The (1995)",0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zeus and Roxanne (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unknown,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Á köldum klaka (Cold Fever) (1994),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

##

In [8]:
y = final_data["movie title"]
y

0                                 Toy Story (1995)
1                                 Toy Story (1995)
2                                 Toy Story (1995)
3                                 Toy Story (1995)
4                                 Toy Story (1995)
                           ...
99994                            Mat' i syn (1997)
99995                             B. Monkey (1998)
99996                         Sliding Doors (1998)
99997                          You So Crazy (1994)
99998    Scream of Stone (Schrei aus Stein) (1991)
Name: movie title, Length: 99999, dtype: str

In [9]:
x = final_data.drop("movie title" , axis=1)
x

       movie_id  user_id  rating
0             1      308       4
1             1      287       5
2             1      148       4
3             1      280       4
4             1       66       3
...         ...      ...     ...
99994      1678      863       1
99995      1679      863       3
99996      1680      863       2
99997      1681      896       3
99998      1682      916       3

[99999 rows x 3 columns]

In [10]:
from sklearn.neighbors import KNeighborsClassifier , NearestNeighbors

In [11]:
model = NearestNeighbors(n_neighbors = 4 , metric = "cosine" , algorithm = "brute")
model

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=4)

In [12]:
model.fit(profile)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=4)

In [45]:
if "101 Dalmatians (1996)" in profile.index:
    print("Y")
else:
    print("N")

Y

In [13]:
indx_no = profile.index.get_loc("101 Dalmatians (1996)")
indx_no

2

In [14]:
distance , indexes = model.kneighbors(profile.iloc[indx_no].values.reshape(1,-1), n_neighbors = 5)

In [15]:
distance

array([[1.11022302e-16, 5.52116615e-01, 5.58117799e-01, 5.76705061e-01,
        5.79357612e-01]])

In [16]:
indexes

array([[   2,  764, 1547, 1633,  744]])

In [18]:
for i in indexes:
    # print(i)
    for j in i :
        print(profile.index[j])

101 Dalmatians (1996)
Jack (1996)
Twister (1996)
Willy Wonka and the Chocolate Factory (1971)
Independence Day (ID4) (1996)